# Generated by Django 4.2.23 on 2025-07-16 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='類型名稱')),
            ],
            options={
                'verbose_name': '合約類型',
                'verbose_name_plural': '合約類型',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='品牌名稱')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='公司名稱')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='聯絡電話')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='合約名稱')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='合約編號')),
                ('type', models.CharField(choices=[('A', 'Type A (主合約)'), ('B', 'Type B (追加合約)')], default='A', max_length=1, verbose_name='主/追加')),
                ('status', models.CharField(choices=[('IN_PROGRESS', '進行中'), ('CLOSED', '已結案'), ('SETTLED', '已結算')], default='IN_PROGRESS', max_length=20, verbose_name='合約狀態')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合約金額')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_stamped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.category', verbose_name='合約類型')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.client', verbose_name='客戶')),
                ('parent_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_contracts', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='contracts.contract')),
            ],
        ),
    ]
